import { User } from './Model';

export const Users = [
  new User({
    firstName: 'vinay',
    lastName: 'dagar',
    followerCont: 20, 
    followingCount: 34,
    userName: 'vinay_dagar_112',
    totalPosts: 5,
    currentStep: 2,
    isProfileCompleted: false,
  }),
  new User({
    firstName: 'vaibhav',
    lastName: 'shokeen',
    followerCont: 120,
    followingCount: 3454,
    userName: 'vaibhav___ss',
    totalPosts: 45,
    isProfileCompleted: true,
  }),
  new User({
    firstName: 'anushka',
    lastName: 'sen',
    followerCont: 15187923,
    followingCount: 16,
    userName: 'anushka.sen5320',
    totalPosts: 766,
    isProfileCompleted: true,
  }),
  new User({
    firstName: 'anupriya',
    lastName: 'bhandari',
    followerCont: 219,
    followingCount: 196,
    userName: 'anu.priya',
    totalPosts: 76,
    isProfileCompleted: true,
  }),
  new User({
    firstName: 'mayank',
    lastName: 'rathi',
    followerCont: 110,
    followingCount: 196,
    userName: 'mayank.rathi12',
    totalPosts: 6,
    isProfileCompleted: true,
  }),
  new User({
    firstName: 'preeti',
    lastName: 'singh',
    followerCont: 110,
    followingCount: 117,
    userName: 'psingh1122',
    totalPosts: 0,
    isProfileCompleted: true,
  }),
];
